apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lead-magnets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scampbell91coaching-dotcom/azure-devops-demo.git
    targetRevision: main
    path: lead-magnets-chart
    helm:
      releaseName: lead-magnets
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
