apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: flask-keyvault-secrets
  namespace: production
spec:
  provider: azure

  secretObjects:
    - secretName: flask-runtime-secrets
      type: Opaque
      data:
        - objectName: applicationinsights-connection-string
          key: APPLICATIONINSIGHTS_CONNECTION_STRING

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "b2f82d29-9835-4461-93dd-26770e00e8cd"
    keyvaultName: "kv-devops-lab-bobcatlion"
    tenantId: "74d2fd2d-dd77-4db5-949c-232b3f50d865"
    objects: |
      array:
        - |
          objectName: flask-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: applicationinsights-connection-string
          objectType: secret
          objectVersion: ""
