{{- if .Values.application.message }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-application
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_DEMO_MESSAGE: {{ .Values.application.message | quote }}
{{- end }}
